

export const CREATE_POST_REQUEST="CREATE_POST_REQUEST"
export const CREATE_POST_SUCCESS="CREATE_POST_SUCCESS"
export const CREATE_POST_FAILURE="CREATE_POST_FAILURE"


export const GET_POST_REQUEST="GET_POST_REQUEST"
export const GET_POST_SUCCESS="GET_POST_SUCCESS"
export const GET_POST_FAILURE="GET_POST_FAILURE"



export const UPDATE_POST_REQUEST="UPDATE_POST_REQUEST"
export const UPDATE_POST_SUCCESS="UPDATE_POST_SUCCESS"
export const UPDATE_POST_FAILURE="UPDATE_POST_FAILURE"


export const GET_POST_BY_ID_REQUEST="GET_POST_BY_ID_REQUEST"
export const GET_POST_BY_ID_SUCCESS="GET_POST_BY_ID_SUCCESS"
export const GET_POST_BY_ID_FAILURE="GET_POST_BY_ID_FAILURE"



export const DELETE_POST_REQUEST="DELETE_POST_REQUEST"
export const DELETE_POST_SUCCESS="DELETE_POST_SUCCESS"
export const DELETE_POST_FAILURE="DELETE_POST_FAILURE"


export const LIKE_POST_REQUEST="LIKE_POST_REQUEST"
export const LIKE_POST_SUCCESS="LIKE_POST_SUCCESS"
export const LIKE_POST_FAILURE="LIKE_POST_FAILURE"


export const DISLIKE_POST_REQUEST="DISLIKE_POST_REQUEST"
export const DISLIKE_POST_SUCCESS="DISLIKE_POST_SUCCESS"
export const DISLIKE_POST_FAILURE="DISLIKE_POST_FAILURE"



export const GET_TOTAL_POST_REQUEST="GET_TOTAL_POST_REQUEST"
export const GET_TOTAL_POST_SUCCESS="GET_TOTAL_POST_SUCCESS"
export const GET_TOTAL_POST_FAILURE="GET_TOTAL_POST_FAILURE"



export const GET_MOST_LIKED_POST_REQUEST="GET_MOST_LIKED_POST_REQUEST"
export const GET_MOST_LIKED_POST_SUCCESS="GET_MOST_LIKED_POST_SUCCESS"
export const GET_MOST_LIKED_POST_FAILURE="GET_MOST_LIKED_POST_FAILURE"